export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_USERDETAIL_REQUEST = 'USER_USERDETAIL_REQUEST'
export const USER_USERDETAIL_SUCCESS = 'USER_USERDETAIL_SUCCESS'
export const USER_USERDETAIL_FAIL = 'USER_USERDETAIL_FAIL'
export const USER_USERDETAIL_RESET = 'USER_USERDETAIL_RESET'

export const USER_UPDATEPROFILE_REQUEST = 'USER_UPDATEPROFILE_REQUEST'
export const USER_UPDATEPROFILE_SUCCESS = 'USER_UPDATEPROFILE_SUCCESS'
export const USER_UPDATEPROFILE_FAIL = 'USER_UPDATEPROFILE_FAIL'
export const USER_UPDATEPROFILE_RESET = 'USER_UPDATEPROFILE_RESET'


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

